### PR TITLE
fix: add `dynamic-import` support flag into esbuild invocation

### LINKED ISSUE #3368: [Bug]: jest-preset-angular does not disable dynamic imports in esbuild, causing Jest to fail on .mjs files
### Version

13.6.1

### Steps to reproduce

1. Clone https://github.com/Markiewic/jest-preset-angular-dynamic-import-reproduction
2. Run `npm install`
3. Run `npm test`
4. See the error

### Expected behavior

No errors, the test passes

### Actual behavior

```
TypeError: A dynamic import callback was invoked without --experimental-vm-modules
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:270:11)
    at Object.<anonymous> (~/vscodeprojects/jest-preset-angular-dynamic-import-reproduction/src/module-with-dynamic-import.mjs:33:19)
    at Runtime._execModule (~/vscodeprojects/jest-preset-angular-dynamic-import-reproduction/node_modules/jest-runtime/build/index.js:1268:24)
    at Runtime._loadModule (~/vscodeprojects/jest-preset-angular-dynamic-import-reproduction/node_modules/jest-runtime/build/index.js:944:12)
    at Runtime.requireModule (~/vscodeprojects/jest-preset-angular-dynamic-import-reproduction/node_modules/jest-runtime/build/index.js:832:12)
    at Runtime.requireModuleOrMock (~/vscodeprojects/jest-preset-angular-dynamic-import-reproduction/node_modules/jest-runtime/build/index.js:964:21)
    at Object.<anonymous> (~/vscodeprojects/jest-preset-angular-dynamic-import-reproduction/src/dynamic-imports.spec.ts:7:42)
    at Runtime._execModule (~/vscodeprojects/jest-preset-angular-dynamic-import-reproduction/node_modules/jest-runtime/build/index.js:1268:24)
    at Runtime._loadModule (~/vscodeprojects/jest-preset-angular-dynamic-import-reproduction/node_modules/jest-runtime/build/index.js:944:12)
    at Runtime.requireModule (~/vscodeprojects/jest-preset-angular-dynamic-import-reproduction/node_modules/jest-runtime/build/index.js:832:12)
    at jestAdapter (~/vscodeprojects/jest-preset-angular-dynamic-import-reproduction/node_modules/jest-circus/build/runner.js:95:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runTestInternal (~/vscodeprojects/jest-preset-angular-dynamic-import-reproduction/node_modules/jest-runner/build/index.js:275:16)
    at async runTest (~/vscodeprojects/jest-preset-angular-dynamic-import-reproduction/node_modules/jest-runner/build/index.js:343:7) {
  code: 'ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING_FLAG'
}
```

### Additional context

In my project, there is a file with dynamic imports in .mjs format: [@taiga-ui/editor](https://www.npmjs.com/package/@taiga-ui/editor?activeTab=code) `fesm2022/taiga-ui-editor-extensions-default-editor-extensions.mjs`.

According to my (default) config, such files should be processed by jest-preset-angular.
The pipeline looks like this:
- jest-preset-angular decides whether to transform the file with esbuild or ts.
- By default, .mjs files go to esbuild, everything else goes to ts.
- esbuild receives the file with dynamic imports and leaves them as-is, even when converting to CJS.

In plain Node.js, this works fine: dynamic imports are allowed in CJS. But Jest executes code inside `vm`, and there dynamic imports are not supported unless you run with `--experimental-vm-modules`. As a result, tests fail.

#### Possible solutions
Add an option [here](https://github.com/thymikee/jest-preset-angular/blob/7740a2da394cb590d5eee6b2248edb1f89b574f1/src/ng-jest-transformer.ts#L82) for esbuild to rewrite dynamic imports into CJS as presented [here](https://github.com/evanw/esbuild/issues/2966#issuecomment-1454527467) (`--supported:dynamic-import=false`). Currently, jest-preset-angular does not allow passing such configuration.

#### Workarounds
- Mock the problematic imports.
- Explicitly force certain files to use ts-jest (works, but not scalable).

### Environment

```shell
System:
    OS: macOS 15.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 20.19.3 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 8.5.1 - /usr/local/bin/pnpm
  npmPackages:
    jest: ^30.2.0 => 30.2.0
```

### PR DESCRIPTION
**Pull request by Markiewic**
## Summary
Added a new field 'dynamic-import' to the esbuild call to transform dynamic imports.

Closes #3368 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: src/ng-jest-transformer.ts [hunk 1]
```diff
@@ -79,9 +79,11 @@ export class NgJestTransformer extends TsJestTransformer {
             this.#ngJestLogger.debug({ filePath }, 'process with esbuild');
 
             const compilerOpts = configSet.parsedTsConfig.options;
+            const useESM = Boolean(transformOptions.supportsStaticESM && configSet.useESM);
```
Comment (ahnpnl) [inline src/ng-jest-transformer.ts:82]:
```suggestion
            const useESM = transformOptions.supportsStaticESM && configSet.useESM;
```
should be good enough, we don't need to explicit casting to `Boolean` :)

**Review by ahnpnl — COMMENTED** [review]
the rest LGTM

File: src/ng-jest-transformer.ts (hunk 1 above)
Comment (Markiewic) [reply src/ng-jest-transformer.ts:82]: I didn't put it at first either, but it turns out in falsy case it's not `false`, but `undefined`. This will have to be added to the mocks, and in my opinion, it will look ugly. Plus, I'm not sure that esbuild won't eventually react to `undefined` differently. But if it's necessary, tell me, I'll remove it.

Comment (ahnpnl) [reply src/ng-jest-transformer.ts:82]: How about we do
```
const useESM = transformOptions.supportsStaticESM && configSet.useESM;

const { code, map } = transformSync(fileContent, {
                loader: 'js',
                format: transformOptions.supportsStaticESM && configSet.useESM ? 'esm' : 'cjs',
                format: useESM ? 'esm' : 'cjs',
                supported: useESM ? { 'dynamic-import': true } : undefined,
```

Comment (Markiewic) [reply src/ng-jest-transformer.ts]: Ah, no, that's not good, we need to explicitly pass `false`. I'll do the opposite.

```js
supported: useESM ? undefined : { 'dynamic-import': false },`
```

**Review by ahnpnl — APPROVED** [review]
Thanks
