### PR TITLE
Fix TS5 + ESM hang; and upgrade dev dependencies to ng17

### LINKED ISSUE #2138: [Bug]: ESM with TypeScript >= 5.0 hangs forever
### Version

13.1.1 (current latest)

### Steps to reproduce

Clone https://github.com/dgp1130/ng-large/tree/jest-preset-angular-esm-bug and run:

```shell
npm ci
npm test # Runs `jest`
```

There's nothing particularly special about this repo. It's basically a brand new `ng new` app on latest Angular where I have attempted to set up `jest-preset-angular` using ESM.

### Expected behavior

Test should pass as there is only one no-op component in the repository.

### Actual behavior

Jest prints:

```
RUNS src/app/app.component.spec.ts
```

And then hangs there forever, never making any meaningful progress.

### Additional context

I'm using the current latest Angular, Jest, Node, and `jest-preset-angular`. Bisecting the versions a bit, I discovered that TypeScript 5.0 introduced the error. TS 4.9.4 does _not_ reproduce, while everything greater than 5.0 (up through 5.1.4, the current latest) fails.

While Jest hangs without an error message, if you open a debugger with `--expose-internals` (`npm run test:debug` in that repo), I was able to find the [failing assertion](https://github.com/microsoft/TypeScript/blob/69d4d57b61b3a5dcc3f9d172c11e0827a47f24fc/src/compiler/debug.ts#L196) which includes the error:

> Unhandled SyntaxKind: ImportClause.

I'm trying to use native ESM here, so I would think TypeScript should emit any imports as effectively a no-op and let Node handle the rest, so I'm not sure why TypeScript is failing to emit the import.

### Environment

```shell
OS: Debian Linux
Node: v18.16.1
Jest: v29.6.1
```

### PR DESCRIPTION
**Pull request by johncrim**
## Summary

I attempted to fix #2138, and as a side effect also upgrade to ng 17, resolving #2196. The main fixes were adding/improving the typescript version detection and version bridging functions so that the breaking changes in TS 5 (that I'm aware of) are handled, without changing the current level of backward compatibility with older versions of typescript and angular.

## Test plan

`yarn test` and `yarn test-examples` all pass (locally).

Tomorrow I will upgrade our projects to ng 17 and TS 5 to verify that our tests no longer hang, as described in #2138.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

Should not be breaking - I did my best to preserve the existing level of backward compatibility.

## Other information

fixes: #2138 
resolves: #2196

### CODE REVIEW

File: src/transformers/replace-resources.ts [hunk 1]
```diff
@@ -136,7 +140,7 @@ function visitClassDeclaration(
         node.heritageClauses,
         node.members,
       )
-    : nodeFactory.updateClassDeclaration(
+    : (nodeFactory as any).updateClassDeclaration(
```
Comment (ahnpnl) [inline src/transformers/replace-resources.ts:143]: Are there other ways we can avoid casting `any`?

**Comment by johncrim** [comment]
@ahnpnl - I had to add `husky` as a dev dependency - the yarn cache build steps were failing b/c it wasn't there. For some reason it wasn't on the `main` that I branched from.

Thanks for the review + guidance.

**Comment by ahnpnl** [comment]
Would you please also add eslint comments to bypass several `Warning:   143:23  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any`, make it look prettier 😃

**Comment by johncrim** [comment]
I can confirm that these updates work as expected on our projects using TS 5.2.2 and ng 17.0.8 and ng 17.0.9.

**Review by ahnpnl — APPROVED** [review]

**Comment by ahnpnl** [comment]
Thanks!

**Comment by johncrim** [comment]
Happy to help! Thank you!

**Comment by michaelfaith** [comment]
Great work on this change!
