### PR TITLE
Transform templateUrl, styleUrls and styles everywhere

### LINKED ISSUE #210: v7 Regression: Component cannot define both template and templateUrl
I tried to do some regression tests on our alpha version. It turned out the fix for `templateUrl` doesn't work for all cases. I attach here an example when it fails with 7.0.0-alpha.1 but works with 6.0.2.

**Step to reproduce**
- Clone the example from https://github.com/ahnpnl/preset-angular-bug
- Install dependencies with `yarn`
- Run test on `alert-follow.component.spec.ts`

**Error log**
```
Error: 'AlertFollowComponent' component cannot define both template and templateUrl

      at syntaxError (../packages/compiler/src/util.ts:100:17)
      at DirectiveNormalizer.Object.<anonymous>.DirectiveNormalizer.normalizeTemplate (../packages/compiler/src/directive_normalizer.ts:68:15)
      at CompileMetadataResolver.Object.<anonymous>.CompileMetadataResolver.loadDirectiveMetadata (../packages/compiler/src/metadata_resolver.ts:260:54)
      at ../packages/compiler/src/jit/compiler.ts:135:36
          at Array.forEach (<anonymous>)
      at ../packages/compiler/src/jit/compiler.ts:133:65
          at Array.forEach (<anonymous>)
      at JitCompiler.Object.<anonymous>.JitCompiler._loadModules (../packages/compiler/src/jit/compiler.ts:130:71)
      at JitCompiler.Object.<anonymous>.JitCompiler._compileModuleAndAllComponents (../packages/compiler/src/jit/compiler.ts:115:32)
      at JitCompiler.Object.<anonymous>.JitCompiler.compileModuleAndAllComponentsSync (../packages/compiler/src/jit/compiler.ts:65:38)
      at CompilerImpl.Object.<anonymous>.CompilerImpl.compileModuleAndAllComponentsSync (../packages/platform-browser-dynamic/src/compiler_factory.ts:60:35)
      at TestingCompilerImpl.Object.<anonymous>.TestingCompilerImpl.compileModuleAndAllComponentsSync (../../packages/platform-browser-dynamic/testing/src/compiler_factory.ts:52:27)
      at TestBedViewEngine.Object.<anonymous>.TestBedViewEngine._initIfNeeded (../../packages/core/testing/src/test_bed.ts:399:28)
      at TestBedViewEngine.Object.<anonymous>.TestBedViewEngine.createComponent (../../packages/core/testing/src/test_bed.ts:602:10)
      at Function.Object.<anonymous>.TestBedViewEngine.createComponent (../../packages/core/testing/src/test_bed.ts:251:36)
      at src/__tests__/components/alert-follow.component.spec.ts:20:23
```

I think ast transformer doesn't understand `overrideComponent` of `TestBed` or something happens there.

cc @wtho @thymikee

### PR DESCRIPTION
**Pull request by wtho**
Closes #210

* Transformer became more simple
* Test was added to verify `templateUrl` gets transformed e. g. in `*.spec.ts` outside a decorator
* Updated the *Preprocessor*-section in `README.md`

:exclamation: Note that it seems the transformer was modified a lot, but basically I just removed code that only looked deep inside decorators. Now it checks everywhere for `stlyes`, `styleUrls` and `templateUrl`.

### CODE REVIEW

**Comment by wtho** [comment]
Note that I added `@types/node` as dev dependency as it was required to compile the transformer via tsc.

File: src/InlineHtmlStripStylesTransformer.ts [hunk 1]
```diff
@@ -203,16 +154,12 @@ export function factory(cs: ConfigSet) {
...
-      if (
-        ts.isClassDeclaration(node) &&
-          node.decorators &&
-          getPropertyAssignmentsToTransform(node).length
-      ) {
+      if (isPropertyAssignmentToTransform(node)) {
         // get mutable node and change properties
         // NOTE: classes can be inside methods, but we do not
         // look for them inside Angular Components!
         // recursion ends here, as ts.visitEachChild is not called.
```
Comment (wtho) [inline src/InlineHtmlStripStylesTransformer.ts]: Update comment

File: src/InlineHtmlStripStylesTransformer.ts [hunk 2]
```diff
@@ -203,16 +154,12 @@ export function factory(cs: ConfigSet) {
 
       // before we create a deep clone to modify, we make sure that
       // this class has the decorator arguments of interest.
```
Comment (wtho) [inline src/InlineHtmlStripStylesTransformer.ts]: This is not about decorators and classes anymore

File: src/InlineHtmlStripStylesTransformer.ts [hunk 3]
```diff
@@ -203,16 +154,12 @@ export function factory(cs: ConfigSet) {
...
+      if (isPropertyAssignmentToTransform(node)) {
         // get mutable node and change properties
         // NOTE: classes can be inside methods, but we do not
         // look for them inside Angular Components!
         // recursion ends here, as ts.visitEachChild is not called.
-        resultNode = transfromDecoratorForJest(node)
+        resultNode = transfromPropertyAssignmentForJest(node)
       } else {
         // look for other classes with decorators
         // classes can be inside other statements (like if blocks)
```
Comment (wtho) [inline src/InlineHtmlStripStylesTransformer.ts]: Update these comments as well

File: src/InlineHtmlStripStylesTransformer.ts [hunk 4]
```diff
@@ -125,65 +86,55 @@ export function factory(cs: ConfigSet) {
...
+  function isPropertyAssignmentToTransform(node: Node): node is PropertyAssignment {
+    return ts.isPropertyAssignment(node) &&
+      ts.isIdentifier(node.name) &&
+      TRANSFORM_PROPS.includes(node.name.text)
   }
 
   /**
    * Clones the node, identifies the properties to transform in the decorator and modifies them.
    * @param node class declaration with decorators
    */
```
Comment (wtho) [inline src/InlineHtmlStripStylesTransformer.ts]: ts docs are outdated - it is not about classes anymore, just about an assignment

**Comment by ahnpnl** [comment]
Lgtm 👍
